# version of config.yaml
version: 0.1.0

appID: "longgui-crm"
appVersion: "0.0.0"
appInstanceID: "050de874-ebbc-47cd-a883-b70c50080513"

# run in AE -> true; run in prod env: -> false
dev: true

# only for prod mod(debug = false)
# database:
#     d1:    # name of database
#         driver: "sqlite3"    # sqlite, sqlite3
#         dsn: "file:test.db"
#     d2:
#         driver: "mysql"
#         dsn: "[username[:password]@][protocol[(address)]]/dbname"
